defmodule OutwardPlanner.Stats.Weapon do
  defstruct [
    :name,
    :class,
    :type,
    :physical,
    :ethereal,
    :fire,
    :frost,
    :lighning,
    :decay,
    :impact,
    :impact_resistance,
    :attackspeed,
    :stamcost,
    :effects,
    :physicalbonus,
    :etherealbonus,
    :firebonus,
    :frostbonus,
    :lightningbonus,
    :decaybonus,
    :manacostreduction,
    :protection,
    :set
  ]
end

# ["name", "Vigilante Dagger"],
# ["class", "Dagger"],
# ["type", "Off-Handed"],
# ["physical", "36"],
# ["ethereal", ""],
# ["fire", ""],
# ["frost", ""],
# ["lightning", ""],
# ["decay", ""],
# ["impact", "52"],
# ["impactResistance", ""],
# ["attackspeed", "1"],
# ["stamcost", ""],
# ["effects", "Crippled"],
# ["physicalBonus", ""],
# ["etherealBonus", ""],
# ["fireBonus", ""],
# ["frostBonus", ""],
# ["lightningBonus", ""],
# ["decayBonus", ""],
# ["manaCostReduction", ""],
# ["protection", "2"],
# ["set", "Vigilante Set"]
